language: ruby
branches:
  only: 
    - master
    - dev
services:
  - postgresql
before_script:
  - cp config/database.yml.travis config/database.yml
  - psql -c 'create database travis_ci_test;' -U postgres
script:
  - bundle exec rake db:migrate --trace
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - bundle exec rake db:test:prepare
  - xvfb-run bundle exec rspec -fd spec/
rvm:
  - 2.3.1
cache: bundler
deploy:
 provider: heroku
 api-key: 
  secure: $HEROKU_API_KEY
 app: seksity
 run:
  - "rake db:migrate"
